---
cisco1:
    hostname: 192.168.1.1
    platform: ios
    site: alderaan
    username: admin
    password: admin
    groups:
      - ios
      - all

juniper1:
    hostname: 192.168.1.3
    platform: junos
    site: endor
    username: admin
    password: admin
    groups:
      - junos
      - all

arista1:
    hostname: 192.168.1.4
    platform: eos
    site: tatooine
    username: admin
    password: admin
    groups:
      - eos
      - all